<?php
// Strings.
$strings = [
    "html_string__demo_home__appnetos_header_two" => "El sistema operativo basado en aplicaciones para aplicaciones web establece nuevos estándares en el desarrollo.",
    "html_string__demo_home__appnetos_text_one" => "APPNET OS ofrece un sistema completo que cubre todo para su aplicación web. Los CMS en varios idiomas facilitan la implementación de aplicaciones en muchos idiomas diferentes.",
    "html_string__demo_home__appnetos_text_two" => "Mediante el uso de aplicaciones como elementos, crear aplicaciones web es más fácil que nunca. El panel Administrador permite que las piezas se configuren individualmente y se asignen a las páginas. La mayoría de las aplicaciones son multilingues y pueden administrar instantáneamente varios idiomas. Debido a la configuración de tamaño, su aplicación web es responsiva con sólo unos pocos clics. En nuestro mercado encontrará muchas aplicaciones geniales con muchas aplicaciones.",
    "html_string__demo_home__appnetos_text_three" => "Administración de usuarios, grupos de usuarios, CMS en varios idiomas, administración de aplicaciones, instalador de aplicaciones, creador de aplicaciones, mercado de aplicaciones, administrador de archivos, correo, sistema de caché avanzada y mucho más.",
    "html_string__demo_home__appnetos_text_four" => "Desarrollar no puede ser más fácil. APPNET OS como marco de trabajo no deja nada que desear. El ingenioso sistema se basa en la lógica más simple, lo que facilita la implementación de grandes proyectos. Las posibilidades son infinitas. Déjese inspirar y arroje un bilck a nuestra extensa documentación.",
    "html_string__demo_home__appnetos_text_five" => "Licenciado bajo la licencia Apache2, el código fuente del sistema operativo APPNET es abierto y gratuito para todos los proyectos.",
    "html_string__demo_home__tools_header" => "Lo mejor de todo unido",
    "html_string__demo_home__tools_header_two" => "APPNET OS combina las mejores herramientas para llegar a su destino de forma fácil, rápida y eficiente.",
    "html_string__demo_home__tools_text_one" => "APPNET OS utiliza el lenguaje de scripting ampliamente utilizado PHP. PHP es perfecto para crear aplicaciones web dinámicas. El lenguaje de programación es fácil de aprender y fácil de usar.  APPNET OS hace que sea aún más fácil de usar PHP. El sistema APP ya prepara la mayor parte de ella, por lo que es fácil de desarrollar.",
    "html_string__demo_home__tools_text_two" => "La biblioteca de JavaScript reutilizada jQuery también es una parte integral del sistema operativo APPNET. jQuery simplifica en gran medida muchas acciones de JavaScript. Gracias a los numerosos plugins, se puede ampliar casi infinitamente. También es relativamente fácil para los principiantes de JavaScript escribir para el código jQuery.",
    "html_string__demo_home__tools_text_three" => "Con Bootstrap, APPNET OS se basa en un marco CSS sólido. Mediante Bootstrap, puede personalizar rápidamente el aspecto de la aplicación web. El sistema de cuadrícula integrado le permite personalizar el tamaño de sus aplicaciones. Con unos pocos clics puede personalizar la salida y crear un resultado responsivo perfecto.",
    "html_string__demo_home__tools_text_four" => "No importa cómo te guste procesar tu salida, APPNET OS puede manejar cualquier cosa. Smarty y Twig son dos motores de plantilla populares y simples. O cree su salida con una plantilla PHP o como un HTML simple. APPNET OS lo representa todo.",
    "html_string__demo_home__more_information" => "Para más información",
    "html_string__demo_home__appnetos_on_github" => "APPNET OS en GitHub",
    "html_string__demo_home__download" => "Descargar",
];