<?php
// Strings.
$strings = [
    "html_string__demo_home__appnetos_header_two" => "Le système d’exploitation basé sur l’application pour les applications Web établit de nouvelles normes en développement.",
    "html_string__demo_home__appnetos_text_one" => "APPNET OS offre un système complet qui couvre tout pour votre application web. Les CMS multilingues facilitent l’implémentage d’applications dans de nombreuses langues différentes.",
    "html_string__demo_home__appnetos_text_two" => "En utilisant les applications comme éléments, la création d’applications Web est plus facile que jamais. Le volet Administrateur permet de configurer les pièces individuellement et d’être attribuées aux pages. La plupart des applications sont multilingues et peuvent gérer instantanément plusieurs langues. En raison des paramètres de taille, votre application web est réactive en quelques clics. Sur notre marché, vous trouverez de nombreuses applications avec de nombreuses applications.",
    "html_string__demo_home__appnetos_text_three" => "Gestion des utilisateurs, groupes d’utilisateurs, CMS multilingue, gestion d’applications, installateur d’applications, créateur d’applications, marché d’applications, gestionnaire de fichiers, expéditeur, système de cache avancé, et plus encore.",
    "html_string__demo_home__appnetos_text_four" => "Le développement ne peut pas être plus facile. APPNET OS comme cadre ne laisse rien à désirer. Le système ingénieux repose sur la logique la plus simple, ce qui facilite la mise en œuvre de grands projets. Les possibilités sont infinies. Laissez-vous inspirer et jetez un bilck dans notre documentation complète.",
    "html_string__demo_home__appnetos_text_five" => "Sous licence Apache2, le code source APPNET OS est ouvert et gratuit pour tous les projets.",
    "html_string__demo_home__tools_header" => "Le meilleur de tout ce qui est uni",
    "html_string__demo_home__tools_header_two" => "APPNET OS combine les meilleurs outils pour se rendre à votre destination facilement, rapidement et efficacement.",
    "html_string__demo_home__tools_text_one" => "APPNET OS utilise le langage de script largement utilisé PHP. PHP est parfait pour créer des applications web dynamiques. Le langage de programmation est facile à apprendre et facile à utiliser.  APPNET OS facilite encore l’utilisation de PHP. Le système APP prépare déjà la plupart de celui-ci, ce qui le rend facile à développer.",
    "html_string__demo_home__tools_text_two" => "La bibliothèque JavaScript réutilise jQuery fait également partie intégrante de l’OS APPNET. jQuery simplifie grandement de nombreuses actions JavaScript. Grâce à de nombreux plugins, il peut être élargi presque à l’infini. Il est également relativement facile pour les débutants JavaScript d’écrire pour le code jQuery.",
    "html_string__demo_home__tools_text_three" => "Avec Bootstrap, APPNET OS s’appuie sur un cadre CSS solide. En utilisant Bootstrap, vous pouvez rapidement personnaliser l’apparence de votre application web. Le système de grille intégré vous permet de personnaliser la taille de vos applications. En quelques clics, vous pouvez personnaliser la sortie et créer un résultat réactif parfait.",
    "html_string__demo_home__tools_text_four" => "Peu importe comment vous aimez traiter votre sortie, APPNET OS peut gérer n’importe quoi. Smarty et Twig sont deux moteurs de modèle populaires et simples. Ou construisez votre sortie avec un modèle PHP ou comme un SIMPLE HTML. APPNET OS rend tout.",
    "html_string__demo_home__more_information" => "Pour plus d’informations",
    "html_string__demo_home__appnetos_on_github" => "APPNET OS sur GitHub",
    "html_string__demo_home__download" => "Télécharger",
];