<?php
/**
 * START LICENSE HEADER
 *
 * The license header may not be removed.
 *
 * This file is a part of APPNET OS (Application Internet Operating System).
 * @link            http://www.appnetos.com
 * @mail            info@appnetos.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @copyright       (C) xtrose Media Studio 2019
 * @author          Moses Rivera
 *                  Im Wiesengrund 24
 *                  73540 Heubach
 * @mail            media.studio@xtrose.de
 *
 * END LICENSE HEADER
 *
 * @description     install/sql/system.php ->    APPNET OS installer sql queries.
 */


// SQL queries.
$queries = [


    // Create table "admin_apps".
    "DROP TABLE IF EXISTS `***PREFIX***_admin_apps`",
    "CREATE TABLE `***PREFIX***_admin_apps` (
      `xt_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'App ID.',
      `xt_active` tinyint(4) NOT NULL DEFAULT '1' COMMENT 'If app is active.',
      `xt_namespace` char(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'App namespace.',
      `xt_directory` char(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'App directory.',
      `xt_name` char(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'App name.',
      `xt_description` varchar(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'App description.',
      `xt_container` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'If app is a container app.',
      `xt_container_grid` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'App bootstrap container grid.',
      `xt_container_css` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'App container css.',
      `xt_container_fluid_css` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'App container fluid css.',
      `xt_app_css` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'App css.',
      `xt_cacheable` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If app is cacheable.',
      `xt_cache` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If app cache is active.',
      `xt_cache_expire` int(10) NOT NULL DEFAULT '0' COMMENT 'App chache expire time.',
      `xt_protected` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'App protection level.',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COMMENT='Administration section apps.'",

    // Insert into table "admin_apps".
    "INSERT INTO `***PREFIX***_admin_apps` VALUES
      (1,1,'admin','','Sign in','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',1,'','','','',0,0,0,3),
      (2,1,'admin\\\\general','general','Components','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (3,1,'admin\\\\menu','menu','Language Menu','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',1,'','','','',0,0,0,3),
      (4,1,'admin\\\\menu','menu','Menu','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (5,1,'admin','','AJAX Error','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (50,1,'admin\\\\dashboard','','Dashboard','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (100,1,'admin\\\\cms','cms','Picker','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (101,1,'admin\\\\apps','apps','Picker','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (102,1,'admin\\\\widgets','widgets','Picker','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (103,1,'admin\\\\cms','cms','Picker Application','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (104,1,'admin\\\\cms','cms','Picker Admin','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (105,1,'admin\\\\groups','groups','Picker Application','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (106,1,'admin\\\\groups','groups','Picker Admin','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (200,1,'admin\\\\users','users','Application Management','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (201,1,'admin\\\\users','users','Admin Management','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (250,1,'admin\\\\groups','groups','Application Groups','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (251,1,'admin\\\\groups','groups','Admin Groups','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (300,1,'admin\\\\cms','cms','URI Management','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (301,1,'admin\\\\cms','cms','Edit URI','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (302,1,'admin\\\\cms','cms','Manage Apps','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (400,1,'admin\\\\apps','apps','Management','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (401,1,'admin\\\\apps','apps','Static Top','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (402,1,'admin\\\\apps','apps','Static Bottom','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (403,1,'admin\\\\apps','apps','Admin','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (404,1,'admin\\\\apps','apps','Create','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (405,1,'admin\\\\apps','apps','Install','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (406,1,'admin\\\\apps','apps','Settings','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (407,1,'admin\\\\apps','apps','Size and Align','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (410,1,'admin\\\\apps','apps','Marketplace','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (500,1,'admin\\\\settings','settings','System','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (501,1,'admin\\\\settings','settings','Languages','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (502,1,'admin\\\\settings','settings','Manage Languages','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (600,1,'admin\\\\mailer','','mailer','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (700,1,'admin\\\\files','files','Management','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3),
      (701,1,'admin\\\\files','files','Settings','SYSTEM APP! IMPORTANT! Do not edit or modify this app or database entry.',0,'','','','',0,0,0,3)",

    // Create table "admin_cms".
    "DROP TABLE IF EXISTS `***PREFIX***_admin_cms`",
    "CREATE TABLE `***PREFIX***_admin_cms` (
      `xt_id` int(10) NOT NULL AUTO_INCREMENT COMMENT 'CMS ID.',
      `xt_parent_id` int(10) NOT NULL DEFAULT '0' COMMENT 'Parent CMS ID.',
      `xt_language_key` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'global' COMMENT 'CMS language key.',
      `xt_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Page title.',
      `xt_favicon` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Page file path to favicon.',
      `xt_uri` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Page SEO URI.',
      `xt_apps` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'CMS apps.',
      `xt_include` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'CMS included apps.',
      `xt_protected` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'CMS protection level.',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=20602 DEFAULT CHARSET=utf8mb4 COMMENT='Administration section CMS.'",

    // Insert into table "admin_cms".
    "INSERT INTO `***PREFIX***_admin_cms` VALUES 
      (1,0,'global','APPNET OS by xtrose Media Studio','out/admin/img/appnetos/favicon-96x96.png','admin','50','3',3),
      (2,0,'global','Manage dashboard','out/admin/img/appnetos/favicon-96x96.png','admin/manage-dashboard','50|102','3',3),
      (100,0,'global','User management','out/admin/img/appnetos/favicon-96x96.png','admin/user/user-management','105|200','3',3),
      (101,0,'global','User groups','out/admin/img/appnetos/favicon-96x96.png','admin/user/user-groups','103|250','3',3),
      (102,0,'global','Aministrator management','out/admin/img/appnetos/favicon-96x96.png','admin/user/admin-management','106|201','3',3),
      (103,0,'global','Aministrator groups','out/admin/img/appnetos/favicon-96x96.png','admin/user/admin-groups','104|251','3',3),
      (200,0,'global','URI management','out/admin/img/appnetos/favicon-96x96.png','admin/cms/uri-management','300','3',3),
      (201,0,'global','Edit URI','out/admin/img/appnetos/favicon-96x96.png','admin/cms/edit-uri','301','3',3),
      (202,0,'global','URI app management','out/admin/img/appnetos/favicon-96x96.png','admin/cms/uri-app-management','302|101','3',3),
      (300,0,'global','App management','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-management','400','3',3),
      (301,0,'global','Static apps top','out/admin/img/appnetos/favicon-96x96.png','admin/apps/static-apps-top','401|101','3',3),
      (302,0,'global','Static apps bottom','out/admin/img/appnetos/favicon-96x96.png','admin/apps/static-apps-bottom','402|101','3',3),
      (303,0,'global','App admin section','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-admin-section','403|100|101','3',3),
      (304,0,'global','Create new app','out/admin/img/appnetos/favicon-96x96.png','admin/apps/create-new-app','404','3',3),
      (305,0,'global','Install apps','out/admin/img/appnetos/favicon-96x96.png','admin/apps/install-apps','405','3',3),
      (306,0,'global','App settings','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-settings','406','3',3),
      (307,0,'global','Edit app size and alignment','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-settings/edit-app-size-and-alignment','406','3',3),
      (308,0,'global','Edit app CSS','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-settings/edit-app-css','406','3',3),
      (309,0,'global','Edit app JavaScript','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-settings/edit-app-javascript','406','3',3),
      (310,0,'global','APPNETOS Marketplace','out/admin/img/appnetos/favicon-96x96.png','admin/apps/marketplace','410','3',3),
      (400,0,'global','System settings','out/admin/img/appnetos/favicon-96x96.png','admin/settings/system-settings','500','3',3),
      (401,0,'global','Language settings','out/admin/img/appnetos/favicon-96x96.png','admin/settings/language-settings','501','3',3),
      (402,0,'global','Language management','out/admin/img/appnetos/favicon-96x96.png','admin/settings/manage-langages','502','3',3),
      (404,0,'global','Cache settings','out/admin/img/appnetos/favicon-96x96.png','admin/settings/cache-settings','500','3',3),
      (405,0,'global','Admin settings','out/admin/img/appnetos/favicon-96x96.png','admin/settings/admin-settings','500','3',3),
      (406,0,'global','Debug settings','out/admin/img/appnetos/favicon-96x96.png','admin/settings/debug-settings','500','3',3),
      (407,0,'global','Class extends','out/admin/img/appnetos/favicon-96x96.png','admin/settings/class-extends','500','3',3),
      (500,0,'global','Mailer logs','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/logs','600','3',3),
      (501,0,'global','Mailer blacklist','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/blacklist','600','3',3),
      (502,0,'global','Mailer whitelist','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/whitelist','600','3',3),
      (503,0,'global','Mailer basic settings','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/basic-settings','600','3',3),
      (504,0,'global','Mailer mailboxes','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/mailboxes','600','3',3),
      (600,0,'global','Files management','out/admin/img/appnetos/favicon-96x96.png','admin/files/management','700','3',3),
      (601,0,'global','Files settings','out/admin/img/appnetos/favicon-96x96.png','admin/files/settings','701','3',3),
      (10001,1,'en','APPNET OS by xtrose Media Studio','out/admin/img/appnetos/favicon-96x96.png','admin','','',3),
      (10002,2,'en','Manage dashboard','out/admin/img/appnetos/favicon-96x96.png','admin/manage-dashboard','','',3),
      (10100,100,'en','User management','out/admin/img/appnetos/favicon-96x96.png','admin/user/user-management','','',3),
      (10101,101,'en','User groups','out/admin/img/appnetos/favicon-96x96.png','admin/user/user-groups','','',3),
      (10102,102,'en','Aministrator management','out/admin/img/appnetos/favicon-96x96.png','admin/user/admin-management','','',3),
      (10103,103,'en','Aministrator groups','out/admin/img/appnetos/favicon-96x96.png','admin/user/admin-groups','','',3),
      (10200,200,'en','URI management','out/admin/img/appnetos/favicon-96x96.png','admin/cms/uri-management','','',3),
      (10201,201,'en','Edit URI','out/admin/img/appnetos/favicon-96x96.png','admin/cms/edit-uri','','',3),
      (10202,202,'en','URI app management','out/admin/img/appnetos/favicon-96x96.png','admin/cms/uri-app-management','','',3),
      (10300,300,'en','App management','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-management','','',3),
      (10301,301,'en','Static apps top','out/admin/img/appnetos/favicon-96x96.png','admin/apps/static-apps-top','','',3),
      (10302,302,'en','Static apps bottom','out/admin/img/appnetos/favicon-96x96.png','admin/apps/static-apps-bottom','','',3),
      (10303,303,'en','App admin section','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-admin-section','','',3),
      (10304,304,'en','Create new app','out/admin/img/appnetos/favicon-96x96.png','admin/apps/create-new-app','','',3),
      (10305,305,'en','Install apps','out/admin/img/appnetos/favicon-96x96.png','admin/blocks/install-apps','','',3),
      (10306,306,'en','App settings','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-settings','','',3),
      (10307,307,'en','Edit app size and alignment','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-settings/edit-app-size-and-alignment','','',3),
      (10308,308,'en','Edit app CSS','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-settings/edit-app-css','','',3),
      (10309,309,'en','Edit app JavaScript','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-settings/edit-app-javascript','','',3),
      (10310,310,'en','APPNETOS Marketplace','out/admin/img/appnetos/favicon-96x96.png','admin/apps/marketplace','','',3),
      (10400,400,'en','System settings','out/admin/img/appnetos/favicon-96x96.png','admin/settings/system-settings','','',3),
      (10401,401,'en','Language settings','out/admin/img/appnetos/favicon-96x96.png','admin/settings/language-settings','','',3),
      (10402,402,'en','Language management','out/admin/img/appnetos/favicon-96x96.png','admin/settings/manage-langages','','',3),
      (10404,404,'en','Cache settings','out/admin/img/appnetos/favicon-96x96.png','admin/settings/cache-settings','','',3),
      (10405,405,'en','Admin settings','out/admin/img/appnetos/favicon-96x96.png','admin/settings/admin-settings','','',3),
      (10406,406,'en','Debug settings','out/admin/img/appnetos/favicon-96x96.png','admin/settings/debug-settings','','',3),
      (10407,407,'en','Class extends','out/admin/img/appnetos/favicon-96x96.png','admin/settings/class-extends','','',3),
      (10500,500,'en','Mailer logs','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/logs','','',3),
      (10501,501,'en','Mailer blacklist','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/blacklist','','',3),
      (10502,502,'en','Mailer whitelist','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/whitelist','','',3),
      (10503,503,'en','Mailer basic settings','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/basic-settings','','',3),
      (10504,504,'en','Mailer mailboxes','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/mailboxes','','',3),
      (10600,600,'en','Files management','out/admin/img/appnetos/favicon-96x96.png','admin/files/management','','',3),
      (10601,601,'en','Files settings','out/admin/img/appnetos/favicon-96x96.png','admin/files/settings','','',3),
      (20001,1,'de','APPNET OS von xtrose Media Studio','out/admin/img/appnetos/favicon-96x96.png','admin','','',3),
      (20002,2,'de','Dashboard verwalten','out/admin/img/appnetos/favicon-96x96.png','admin/dashboard-verwalten','','',3),
      (20100,100,'de','Benutzerverwaltung','out/admin/img/appnetos/favicon-96x96.png','admin/benutzer/benutzerverwaltung','','',3),
      (20101,101,'de','Benutzergruppen','out/admin/img/appnetos/favicon-96x96.png','admin/user/benutzergruppen','','',3),
      (20102,102,'de','Aministratorverwaltung','out/admin/img/appnetos/favicon-96x96.png','admin/user/admin-verwaltung','','',3),
      (20103,103,'de','Aministratorgruppen','out/admin/img/appnetos/favicon-96x96.png','admin/user/admin-gruppen','','',3),
      (20200,200,'de','URI Verwaltung','out/admin/img/appnetos/favicon-96x96.png','admin/cms/uri-verwaltung','','',3),
      (20201,201,'de','URI bearbeiten','out/admin/img/appnetos/favicon-96x96.png','admin/cms/uri-bearbeiten','','',3),
      (20202,202,'de','URI App Verwaltung','out/admin/img/appnetos/favicon-96x96.png','admin/cms/uri-app-verwaltung','','',3),
      (20300,300,'de','App Verwaltung','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-verwaltung','','',3),
      (20301,301,'de','Statische Apps oben','out/admin/img/appnetos/favicon-96x96.png','admin/apps/statische-apps-oben','','',3),
      (20302,302,'de','Statische Apps unten','out/admin/img/appnetos/favicon-96x96.png','admin/apps/statische-apps-unten','','',3),
      (20303,303,'de','App Admin Bereich','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-admin-bereich','','',3),
      (20304,304,'de','Neuen App erstellen','out/admin/img/appnetos/favicon-96x96.png','admin/app/neue-app-erstellen','','',3),
      (20305,305,'de','Apps installieren','out/admin/img/appnetos/favicon-96x96.png','admin/apps/apps-installieren','','',3),
      (20306,306,'de','App Einstellungen','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-einstellungen','','',3),
      (20307,307,'de','App Größe und Ausrichtung bearbeiten','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-einstellungen/app-größe-und-ausrichtung-bearbeiten','','',3),
      (20308,308,'de','App CSS bearbeiten','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-einstellungen/app-css-bearbeiten','','',3),
      (20309,309,'de','App JavaScript bearbeiten','out/admin/img/appnetos/favicon-96x96.png','admin/apps/app-einstellungen/app-javascript-bearbeiten','','',3),
      (20310,310,'de','APPNET OS Marktplatz','out/admin/img/appnetos/favicon-96x96.png','admin/apps/marktplatz','','',3),
      (20400,400,'de','System Einstellungen','out/admin/img/appnetos/favicon-96x96.png','admin/einstellungen/system-einstellungen','','',3),
      (20401,401,'de','Spracheinstellungen','out/admin/img/appnetos/favicon-96x96.png','admin/einstellungen/spracheinstellungen','','',3),
      (20402,402,'de','Sprachen verwalten','out/admin/img/appnetos/favicon-96x96.png','admin/einstellungen/sprachen-verwalten','','',3),
      (20404,404,'de','Cache Einstellungen','out/admin/img/appnetos/favicon-96x96.png','admin/einstellungen/cache-einstellungen','','',3),
      (20405,405,'de','Admin Einstellungen','out/admin/img/appnetos/favicon-96x96.png','admin/einstellungen/admin-einstellungen','','',3),
      (20406,406,'de','Debug Einstellungen','out/admin/img/appnetos/favicon-96x96.png','admin/einstellungen/debug-einstellungen','','',3),
      (20407,407,'de','Klassen-Erweiterungen','out/admin/img/appnetos/favicon-96x96.png','admin/einstellungen/klassen-erweiterungen','','',3),
      (20500,500,'de','Mailer Logs','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/logs','','',3),
      (20501,501,'de','Mailer Blacklist','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/blacklist','','',3),
      (20502,502,'de','Mailer Whitelist','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/whitelist','','',3),
      (20503,503,'de','Mailer Einstellungen','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/einstellungen','','',3),
      (20504,504,'de','Mailer Postfächer','out/admin/img/appnetos/favicon-96x96.png','admin/mailer/postfächer','','',3),
      (20600,600,'de','Dateiverwaltung','out/admin/img/appnetos/favicon-96x96.png','admin/dateien/dateiverwaltung','','',3),
      (20601,601,'de','Dateien Einstellungen','out/admin/img/appnetos/favicon-96x96.png','admin/dateien/einstellungen','','',3)",

    // Create table "admin_groups".
    "DROP TABLE IF EXISTS `***PREFIX***_admin_groups`",
    "CREATE TABLE `***PREFIX***_admin_groups` (
      `xt_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Group ID.',
      `xt_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Group name.',
      `xt_granted` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Granted CMS IDs.',
      `xt_denied` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Denied CMS IDs.',
      `xt_default` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If is default group.',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='Administration section user groups.'",

    // Insert into table "admin_groups".
    "INSERT INTO `***PREFIX***_admin_groups` VALUES (1,'Admin Group 1','','',1)",

    // Create table "admin_static".
    "DROP TABLE IF EXISTS `***PREFIX***_admin_static`",
    "CREATE TABLE `***PREFIX***_admin_static` (
      `xt_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Set ID.',
      `xt_top` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Static apps on top.',
      `xt_bottom` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Static apps on bottom',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='Administration section static apps.'",

    // Insert into table "admin_static".
    "INSERT INTO `***PREFIX***_admin_static` VALUES (1,'2|4','')",

    // Create table "admin_users".
    "DROP TABLE IF EXISTS `***PREFIX***_admin_users`",
    "CREATE TABLE `***PREFIX***_admin_users` (
      `xt_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Administrator ID.',
      `xt_user` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Administrator name.',
      `xt_pass` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Administrator password.',
      `xt_pass_salt` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Administrator password salt.',
      `xt_mail` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Administrator email address.',
      `xt_image` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Administrator image.',
      `xt_active` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If administrator is active.',
      `xt_sign_in_count` int(11) NOT NULL DEFAULT '0' COMMENT 'Administrator sign in count.',
      `xt_error_count` int(11) NOT NULL DEFAULT '0' COMMENT 'Administrator sign in error count.',
      `xt_ip_last` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'IP on last sign in.',
      `xt_ts_last` int(11) NOT NULL DEFAULT '0' COMMENT 'Timestamp last sign in.',
      `xt_group` int(11) NOT NULL DEFAULT '0' COMMENT 'Administrator group.',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='Administration section users.'",
    
    // Create table "app_extensions".
    "DROP TABLE IF EXISTS `***PREFIX***_app_extensions`",
    "CREATE TABLE `***PREFIX***_app_extensions` (
      `xt_id` int(10) NOT NULL AUTO_INCREMENT COMMENT 'App extensions ID.',
      `xt_key` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'App key (MD5 App \"namespace\\app name\").',
      `xt_index` int(10) NOT NULL DEFAULT '1' COMMENT 'App extension index.',
      `xt_tinyint` tinyint(4) DEFAULT NULL COMMENT 'Extended app data as tinyint.',
      `xt_int` int(255) DEFAULT NULL COMMENT 'Extended app data as int.',
      `xt_varchar` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Extended app data as varchar with maximum of 255 signs.',
      `xt_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Extended app data as text.',
      `xt_longtext` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Extended app data as longtext.',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COMMENT='Extended app data for app settings.'",

    // Insert into table "app_extensions".
    "INSERT INTO `***PREFIX***_app_extensions` VALUES 
      (1,'6220a1ad2650b388eb49085e93c5882f',1,NULL,NULL,NULL,NULL,'[{\"uuid\":\"E43DD949-1722-4D02-8084-E062EF025708\",\"name\":\"{home}\",\"appsList\":[400,401,300,1200]}]'),
      (2,'28c183fa73ff7b5aed4049094be1e313',102,NULL,NULL,NULL,'{\\\"design\\\":\\\"light\\\",\\\"home\\\":false,\\\"logon\\\":true,\\\"signup\\\":8,\\\"forgetPass\\\":14}',NULL),
      (3,'f8720d31089640a6c3eaf62ddcd13362',2,NULL,NULL,NULL,'{\\\"mailbox\\\":null,\\\"force\\\":true,\\\"terms\\\":null,\\\"name\\\":\\\"APPNET OS\\\"}',NULL),
      (4,'b8853b381b115534a09bd1493bb84aea',1,NULL,NULL,NULL,'{\\\"signup\\\":8,\\\"forgetPass\\\":14}',NULL)",

    // Create table "application_apps".
    "DROP TABLE IF EXISTS `***PREFIX***_application_apps`",
    "CREATE TABLE `***PREFIX***_application_apps` (
      `xt_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'App ID.',
      `xt_active` tinyint(4) NOT NULL DEFAULT '1' COMMENT 'If app is active.',
      `xt_namespace` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'App namespace.',
      `xt_directory` char(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'App directory.',
      `xt_name` char(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'App name.',
      `xt_description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Personal app description.',
      `xt_widget` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If app has a widget.',
      `xt_container` tinyint(4) NOT NULL DEFAULT '1' COMMENT 'If app is a container app.',
      `xt_container_grid` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'App bootstrap container grid.',
      `xt_container_css` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'App container css.',
      `xt_container_fluid_css` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'App container fluid css.',
      `xt_app_css` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'App css.',
      `xt_cacheable` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'If app is cacheable.',
      `xt_cache` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If app cache is active.',
      `xt_cache_expire` int(10) NOT NULL DEFAULT '0' COMMENT 'App cache expire time.',
      `xt_js_cache` tinyint(4) NOT NULL DEFAULT '1' COMMENT 'If app JavaScript cache is active.',
      `xt_css_cache` tinyint(4) NOT NULL DEFAULT '1' COMMENT 'If app CSS cache is active',
      `xt_protected` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'App protection level.',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=1005 DEFAULT CHARSET=utf8mb4 COMMENT='Application section apps.'",

    // Insert into table "application_apps".
    "INSERT INTO `***PREFIX***_application_apps` VALUES 
      (1,1,'appnetos','appnetos','Sign In Form','APPNET OS :: Sign in form ',0,1,'offset-0 col-12 offset-sm-1 col-sm-10 offset-md-0 col-md-6 offset-lg-0 col-lg-5 offset-xl-0 col-xl-4','','','',0,0,0,1,1,0),
      (2,1,'appnetos','appnetos','Sign Up Form','APPNET OS :: Sign up form',0,1,'','','','',0,0,0,1,1,0),
      (3,1,'appnetos','appnetos','Forgotten Password Form','APPNET OS :: Forgotten password form',0,1,'offset-0 col-12 offset-sm-1 col-sm-10 offset-md-0 col-md-6 offset-lg-0 col-lg-5 offset-xl-0 col-xl-4','','','',0,0,0,1,1,0),
      (4,1,'appnetos','appnetos','Change Password Form','APPNET OS :: Change password form',0,1,'','','','',0,0,0,1,1,0),
      (5,1,'appnetos','appnetos','Force Sign In','APPNET OS :: Force sign in',0,0,'','','','',0,0,0,1,1,0),
      (10,1,'appnetos','appnetos','Contact Form','APPNET OS :: Contact form',0,1,'','','','',0,0,0,1,1,0),
      (100,1,'appnetos','appnetos','Cookie Note','APPNET OS :: Cookie Note',0,1,'','','','',0,0,0,1,1,0),
      (101,1,'appnetos','appnetos','Language Menu','APPNET OS :: Language Menu',0,1,'','','','mt-2',1,0,3600,1,1,0),
      (102,1,'appnetos','appnetos','Navbar','APPNET OS Demo :: Navbar',0,1,'','','bg-light','',0,0,0,1,1,0),
      (103,1,'appnetos','appnetos','Header','APPNET OS Demo :: Header',0,1,'','','bg-dark','',1,0,3600,1,1,0),
      (104,1,'appnetos','appnetos','Carousel','APPNET OS :: Carousel',0,1,'','','','',1,0,0,1,1,0),
      (105,1,'appnetos','appnetos','Breadcrumbs','APPNET OS :: Breadcrumbs',0,1,'','','','',1,0,0,1,1,0),
      (300,1,'appnetos','appnetos','Mailer','APPNET OS :: Mailer',1,0,'','','','',0,0,0,1,1,0),
      (400,1,'appnetos\\\\widgets','appnetos','Widget Apps','APPNET OS :: Widget Apps',1,0,'','','','',0,0,0,1,1,0),
      (401,1,'appnetos\\\\widgets','appnetos','Widget Cache','APPNET OS :: Widget Cache',1,0,'','','','',0,0,0,1,1,0),
      (600,1,'appnetos','appnetos','Container End','APPNET OS :: Container End',0,0,'','','','',0,0,0,1,1,0),
      (800,1,'appnetos','appnetos','Font Awesome Free','APPNET OS :: Font awesome Free',0,0,'','','','',0,0,0,1,1,0),
      (1001,1,'appnetos\\\\html_string\\\\demo_home','html_string','Demo Home','APPNET OS :: Demo Home',0,1,'','','','',0,0,0,1,1,0),
      (1002,1,'appnetos\\html_string\\demo_sign_in','html_string','Demo Sign In','APPNET OS :: Demo Sign In',0,1,'offset-0 col-12 offset-sm-1 col-sm-10 offset-md-0 col-md-6 offset-lg-1 col-lg-5 offset-xl-2 col-xl-4','','mt-5','mb-5',1,0,0,1,1,0),
      (1003,1,'appnetos\\html_string\\demo_sign_up','html_string','Demo Sign Up','APPNET OS :: Demo Sign Up',0,1,'','','','',1,0,0,1,1,0),
      (1004,1,'appnetos\\html_string\\demo_forgotten_password','html_string','Demo Forgotten Password','APPNET OS :: Forgotten Password',0,1,'offset-0 col-12 offset-sm-1 col-sm-10 offset-md-0 col-md-6 offset-lg-1 col-lg-5 offset-xl-2 col-xl-4','','mt-5','mb-5',1,0,0,1,1,0),
      (1200,1,'appnetos\\\\widgets','appnetos','Widget Remove Demo','APPNET OS :: Widget Remove Demo',1,0,'','','','',0,0,0,1,1,0)",

    // Create table "application_authentication".
    "DROP TABLE IF EXISTS `***PREFIX***_application_authentication`",
    "CREATE TABLE `***PREFIX***_application_authentication` (
      `xt_token` char(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Authentication token.',
      `xt_user` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'User name.',
      `xt_pass` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'User password.',
      `xt_mail` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'User email address.',
      `xt_user_agent` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Browser user agent.',
      `xt_ts` int(11) NOT NULL COMMENT 'Authentication timestamp.',
      UNIQUE KEY `***PREFIX***_application_authentication_xt_token_uindex` (`xt_token`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Application section user authentication.'",

    // Create table "application_cache".
    "DROP TABLE IF EXISTS `***PREFIX***_application_cache`",
    "CREATE TABLE `***PREFIX***_application_cache` (
      `xt_id` char(32) CHARACTER SET latin1 NOT NULL COMMENT 'Chache ID.',
      `xt_expire` int(20) NOT NULL COMMENT 'Chache expire time.',
      `xt_content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Cache content.'
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Application section app chache data.'",

    // Create table "application_cms".
    "DROP TABLE IF EXISTS `***PREFIX***_application_cms`",
    "CREATE TABLE `***PREFIX***_application_cms` (
      `xt_id` int(10) NOT NULL AUTO_INCREMENT COMMENT 'CMS ID.',
      `xt_parent_id` int(10) NOT NULL DEFAULT '0' COMMENT 'Parent CMS ID.',
      `xt_language_key` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'global' COMMENT 'CMS language key.',
      `xt_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Page title.',
      `xt_favicon` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Page file path to favicon.',
      `xt_canonical_id` int(10) NOT NULL DEFAULT '0' COMMENT 'Page canonical CMS ID.',
      `xt_uri` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Page SEO URI.',
      `xt_apps` varchar(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'CMS apps.',
      `xt_include` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'CMS included apps.',
      `xt_meta` varchar(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'Page meta data as JSON.',
      `xt_protected` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'CMS protection level.',
      `xt_views` int(10) NOT NULL DEFAULT '0' COMMENT 'Page views.',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Application section CMS.'",

    // Insert into table "application_cms".
    "INSERT INTO `***PREFIX***_application_cms` VALUES 
      (1,0,'global','','',0,'','1001','','',0,0),
      (2,0,'global','Sign in','',0,'sign-in','1002|1','','',0,0),
      (3,2,'de','Anmelden','',0,'anmelden','','','',0,0),
      (4,2,'es','Inicia sesión','',0,'inicia-sesión','','','',0,0),
      (5,2,'fr','Connexion','',0,'connexion','','','',0,0),
      (6,2,'it','Accedi','',0,'accedi','','','',0,0),
      (7,2,'ru','Войти','',0,'bойти','','','',0,0),
      (8,0,'global','Sign up','',0,'sign-up','1003','2','',0,0),
      (9,8,'de','Registrieren','',0,'registrieren','','','',0,0),
      (10,8,'es','registro','',0,'registro-es','','','',0,0),
      (11,8,'fr','S’inscrire','',0,'s-inscrire','','','',0,0),
      (12,8,'it','Registro','',0,'registro-it','','','',0,0),
      (13,8,'ru','Зарегистрировать','',0,'зарегистрировать','','','',0,0),
      (14,0,'global','Forgotten password','',0,'forgotten-password','300|1004|3','','',0,0),
      (15,14,'de','Passwort vergessen','',0,'passwort-vergessen','','','',0,0),
      (16,14,'es','Contraseña olvidada','',0,'contraseña-olvidada','','','',0,0),
      (17,14,'fr','Mot de passe oublié','',0,'mot-de-passe-oublié','','','',0,0),
      (18,14,'it','Password dimenticata','',0,'password-dimenticata','','','',0,0),
      (19,14,'ru','Забытый пароль','',0,'забытый-пароль','','','',0,0)",

    // Create table "application_groups".
    "DROP TABLE IF EXISTS `***PREFIX***_application_groups`",
    "CREATE TABLE `***PREFIX***_application_groups` (
      `xt_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Group ID.',
      `xt_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Group name.',
      `xt_granted` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Granted CMS IDs.',
      `xt_denied` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Denied CMS IDs.',
      `xt_default` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If is default group.',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='Application section user groups.'",

    // Insert into table "application_groups".
    "INSERT INTO `***PREFIX***_application_groups` VALUES (1,'User group 1','','',1)",

    // Create table "application_static".
    "DROP TABLE IF EXISTS `***PREFIX***_application_static`",
    "CREATE TABLE `***PREFIX***_application_static` (
      `xt_id` int(10) NOT NULL AUTO_INCREMENT COMMENT 'Set ID.',
      `xt_top` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Static apps on top.',
      `xt_bottom` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Static apps on bottom.',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Application section static apps.'",

    // Insert into table "application_static".
    "INSERT INTO `***PREFIX***_application_static` VALUES (1,'103|600|102|600|101|600','')",

    // Create table "application_users".
    "DROP TABLE IF EXISTS `***PREFIX***_application_users`",
    "CREATE TABLE `***PREFIX***_application_users` (
      `xt_id` int(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'User ID.',
      `xt_user` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'User name.',
      `xt_user_lower` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'User name in lower characters.',
      `xt_pass` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'User password.',
      `xt_pass_salt` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'User password salt.',
      `xt_mail` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'User email address.',
      `xt_image` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'User image.',
      `xt_active` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If user is active.',
      `xt_sign_in_count` int(20) NOT NULL DEFAULT '0' COMMENT 'User sign in count.',
      `xt_error_count` int(10) NOT NULL DEFAULT '0' COMMENT 'User sign in error count.',
      `xt_ip_first` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'IP on sign up.',
      `xt_ts_first` int(11) NOT NULL DEFAULT '0' COMMENT 'Timestamp on sign up.',
      `xt_ip_last` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'IP on last sign in.',
      `xt_ts_last` int(11) NOT NULL DEFAULT '0' COMMENT 'Timestamp on last sign in.',
      `xt_locked` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If user is locked.',
      `xt_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If user is deleted.',
      `xt_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Registration and password reset code.',
      `xt_reset` int(11) NOT NULL DEFAULT '0' COMMENT 'If user has reset his password.',
      `xt_group` int(11) NOT NULL DEFAULT '0' COMMENT 'User group.',
      `xt_data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Extended user data as JSON.',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='Application section users.'",

    // Create table "languages".
    "DROP TABLE IF EXISTS `***PREFIX***_languages`",
    "CREATE TABLE `***PREFIX***_languages` (
      `xt_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Language ID.',
      `xt_key` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Langauge key.',
      `xt_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Language name.',
      `xt_name_en` char(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'English language name.',
      `xt_active` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If language is active in application section.',
      `xt_default` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If is default language in application section.',
      `xt_title` char(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Default page title in application section.',
      `xt_favicon` char(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Default page favicon in application section.',
      `xt_admin_active` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'If language is active in administration section.',
      `xt_admin_default` int(11) NOT NULL DEFAULT '0' COMMENT 'If is default language in administration section.',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=436 DEFAULT CHARSET=utf8mb4 COMMENT='APPNET OS languages for application and administration section.'",

    // Insert into table "langauges".
    "INSERT INTO `***PREFIX***_languages` VALUES 
      (1,'global','','Global',1,0,'APPNET OS','out/img/www.appnetos.com/favicon.png',1,1),
      (2,'af_NA','Afrikaans (Namibia)','Afrikaans (Namibia)',0,0,'','',0,0),
      (3,'af_ZA','Afrikaans (Suid-Afrika)','Afrikaans (South Africa)',0,0,'','',0,0),
      (4,'af','Afrikaans','Afrikaans',0,0,'','',0,0),
      (5,'ak_GH','','Akan (Ghana)',0,0,'','',0,0),
      (6,'ak','','Akan',0,0,'','',0,0),
      (7,'sq_AL','Shqiptare (Shqiperi)','Albanian (Albania)',0,0,'','',0,0),
      (8,'sq','Shqiptare','Albanian',0,0,'','',0,0),
      (9,'am_ET','አማርኛ (ኢትዮጵያ)','Amharic (Ethiopia)',0,0,'','',0,0),
      (10,'am','አማርኛ','Amharic',0,0,'','',0,0),
      (11,'ar_DZ','العربية (الجزائر)','Arabic (Algeria)',0,0,'','',0,0),
      (12,'ar_BH','العربية (البحرين)','Arabic (Bahrain)',0,0,'','',0,0),
      (13,'ar_EG','العربية (مصر)','Arabic (Egypt)',0,0,'','',0,0),
      (14,'ar_IQ','العربية (العراق)','Arabic (Iraq)',0,0,'','',0,0),
      (15,'ar_JO','العربية (الأردن)','Arabic (Jordan)',0,0,'','',0,0),
      (16,'ar_KW','العربية (الكويت)','Arabic (Kuwait)',0,0,'','',0,0),
      (17,'ar_LB','العربية (لبنان)','Arabic (Lebanon)',0,0,'','',0,0),
      (18,'ar_LY','العربية (ليبيا)','Arabic (Libya)',0,0,'','',0,0),
      (19,'ar_MA','العربية (المغرب)','Arabic (Morocco)',0,0,'','',0,0),
      (20,'ar_OM','العربية (عمان)','Arabic (Oman)',0,0,'','',0,0),
      (21,'ar_QA','العربية (قطر)','Arabic (Qatar)',0,0,'','',0,0),
      (22,'ar_SA','العربية (السعودية)','Arabic (Saudi Arabia)',0,0,'','',0,0),
      (23,'ar_SD','العربية (السودان)','Arabic (Sudan)',0,0,'','',0,0),
      (24,'ar_SY','العربية (سوريا)','Arabic (Syria)',0,0,'','',0,0),
      (25,'ar_TN','العربية (تونس)','Arabic (Tunisia)',0,0,'','',0,0),
      (26,'ar_AE','العربية (الإمارات العربية المتحدة)','Arabic (United Arab Emirates)',0,0,'','',0,0),
      (27,'ar_YE','العربية (اليمن)','Arabic (Yemen)',0,0,'','',0,0),
      (28,'ar','عربى','Arabic',0,0,'','',0,0),
      (29,'hy_AM','Հայ (Հայաստան)','Armenian (Armenia)',0,0,'','',0,0),
      (30,'hy','հայերեն','Armenian',0,0,'','',0,0),
      (31,'as_IN','','Assamese (India)',0,0,'','',0,0),
      (32,'as','','Assamese',0,0,'','',0,0),
      (33,'asa_TZ','','Asu (Tanzania)',0,0,'','',0,0),
      (34,'asa','','Asu',0,0,'','',0,0),
      (35,'az_Cyrl','Azərbaycan (Kiril)','Azerbaijani (Cyrillic)',0,0,'','',0,0),
      (36,'az_Cyrl_AZ','Azərbaycan dili (Kiril, Azərbaycan)','Azerbaijani (Cyrillic, Azerbaijan)',0,0,'','',0,0),
      (37,'az_Latn','Azərbaycan (Latın)','Azerbaijani (Latin)',0,0,'','',0,0),
      (38,'az_Latn_AZ','Azərbaycan (Latın, Azərbaycan)','Azerbaijani (Latin, Azerbaijan)',0,0,'','',0,0),
      (39,'az','Azərbaycan','Azerbaijani',0,0,'','',0,0),
      (40,'bm_ML','','Bambara (Mali)',0,0,'','',0,0),
      (41,'bm','','Bambara',0,0,'','',0,0),
      (42,'eu_ES','Euskal (Espainia)','Basque (Spain)',0,0,'','',0,0),
      (43,'eu','Euskal','Basque',0,0,'','',0,0),
      (44,'be_BY','Беларуская (Беларусь)','Belarusian (Belarus)',0,0,'','',0,0),
      (45,'be','Беларуская','Belarusian',0,0,'','',0,0),
      (46,'bem_ZM','','Bemba (Zambia)',0,0,'','',0,0),
      (47,'bem','','Bemba',0,0,'','',0,0),
      (48,'bez_TZ','','Bena (Tanzania)',0,0,'','',0,0),
      (49,'bez','','Bena',0,0,'','',0,0),
      (50,'bn_BD','বাংলা (বাংলাদেশ)','Bengali (Bangladesh)',0,0,'','',0,0),
      (51,'bn_IN','বাংলা (ভারত)','Bengali (India)',0,0,'','',0,0),
      (52,'bn','বাংলা','Bengali',0,0,'','',0,0),
      (53,'bs_BA','Bosanski (Bosna i Hercegovina)','Bosnian (Bosnia and Herzegovina)',0,0,'','',0,0),
      (54,'bs','Bosanski','Bosnian',0,0,'','',0,0),
      (55,'bg_BG','Български (България)','Bulgarian (Bulgaria)',0,0,'','',0,0),
      (56,'bg','български','Bulgarian',0,0,'','',0,0),
      (57,'my_MM','မြန်မာ (မြန်မာ [မြန်မာနိုင်ငံ])','Burmese (Myanmar [Burma])',0,0,'','',0,0),
      (58,'my','မြန်မာ','Burmese',0,0,'','',0,0),
      (59,'ca_ES','Català (Espanya)','Catalan (Spain)',0,0,'','',0,0),
      (60,'ca','Català','Catalan',0,0,'','',0,0),
      (61,'tzm_Latn','','Central Morocco Tamazight (Latin)',0,0,'','',0,0),
      (62,'tzm_Latn_MA','','Central Morocco Tamazight (Latin, Morocco)',0,0,'','',0,0),
      (63,'tzm','','Central Morocco Tamazight',0,0,'','',0,0),
      (64,'chr_US','','Cherokee (United States)',0,0,'','',0,0),
      (65,'chr','','Cherokee',0,0,'','',0,0),
      (66,'cgg_UG','','Chiga (Uganda)',0,0,'','',0,0),
      (67,'cgg','','Chiga',0,0,'','',0,0),
      (68,'zh_Hans','中文（简体汉）','Chinese (Simplified Han)',0,0,'','',0,0),
      (69,'zh_Hans_CN','中文（简体汉，中国）','Chinese (Simplified Han, China)',0,0,'','',0,0),
      (70,'zh_Hans_HK','中文（简体汉，中国香港特别行政区）','Chinese (Simplified Han, Hong Kong SAR China)',0,0,'','',0,0),
      (71,'zh_Hans_MO','中文（简体汉，澳门特别行政区中国）','Chinese (Simplified Han, Macau SAR China)',0,0,'','',0,0),
      (72,'zh_Hans_SG','中文（简体汉，新加坡）','Chinese (Simplified Han, Singapore)',0,0,'','',0,0),
      (73,'zh_Hant','中國人（繁體漢族）','Chinese (Traditional Han)',0,0,'','',0,0),
      (74,'zh_Hant_HK','中文（漢族，中國香港特別行政區）','Chinese (Traditional Han, Hong Kong SAR China)',0,0,'','',0,0),
      (75,'zh_Hant_MO','中文（韓國傳統漢族，中國）','Chinese (Traditional Han, Macau SAR China)',0,0,'','',0,0),
      (76,'zh_Hant_TW','中文（繁體漢，台灣）','Chinese (Traditional Han, Taiwan)',0,0,'','',0,0),
      (77,'zh','中文','Chinese',0,0,'','',0,0),
      (78,'kw_GB','','Cornish (United Kingdom)',0,0,'','',0,0),
      (79,'kw','','Cornish',0,0,'','',0,0),
      (80,'hr_HR','Hrvatski (Hrvatska)','Croatian (Croatia)',0,0,'','',0,0),
      (81,'hr','Hrvatski','Croatian',0,0,'','',0,0),
      (82,'cs_CZ','Česky (Česká republika)','Czech (Czech Republic)',0,0,'','',0,0),
      (83,'cs','Česky','Czech',0,0,'','',0,0),
      (84,'da_DK','Dansk (danmark)','Danish (Denmark)',0,0,'','',0,0),
      (85,'da','Dansk','Danish',0,0,'','',0,0),
      (86,'nl_BE','Nederlands (België)','Dutch (Belgium)',0,0,'','',0,0),
      (87,'nl_NL','Nederlands (Nederland)','Dutch (Netherlands)',0,0,'','',0,0),
      (88,'nl','Nederlands','Dutch',0,0,'','',0,0),
      (89,'ebu_KE','','Embu (Kenya)',0,0,'','',0,0),
      (90,'ebu','','Embu',0,0,'','',0,0),
      (91,'en_AS','English (American Samoa)','English (American Samoa)',0,0,'','',0,0),
      (92,'en_AU','English (Australia)','English (Australia)',0,0,'','',0,0),
      (93,'en_BE','English (Belgium)','English (Belgium)',0,0,'','',0,0),
      (94,'en_BZ','English (Belize)','English (Belize)',0,0,'','',0,0),
      (95,'en_BW','English (Botswana)','English (Botswana)',0,0,'','',0,0),
      (96,'en_CA','English (Canada)','English (Canada)',0,0,'','',0,0),
      (97,'en_GU','English (Guam)','English (Guam)',0,0,'','',0,0),
      (98,'en_HK','English (Hong Kong SAR China)','English (Hong Kong SAR China)',0,0,'','',0,0),
      (99,'en_IN','English (India)','English (India)',0,0,'','',0,0),
      (100,'en_IE','English (Ireland)','English (Ireland)',0,0,'','',0,0),
      (101,'en_JM','English (Jamaica)','English (Jamaica)',0,0,'','',0,0),
      (102,'en_MT','English (Malta)','English (Malta)',0,0,'','',0,0),
      (103,'en_MH','English (Marshall Islands)','English (Marshall Islands)',0,0,'','',0,0),
      (104,'en_MU','English (Mauritius)','English (Mauritius)',0,0,'','',0,0),
      (105,'en_NA','English (Namibia)','English (Namibia)',0,0,'','',0,0),
      (106,'en_NZ','English (New Zealand)','English (New Zealand)',0,0,'','',0,0),
      (107,'en_MP','English (Northern Mariana Islands)','English (Northern Mariana Islands)',0,0,'','',0,0),
      (108,'en_PK','English (Pakistan)','English (Pakistan)',0,0,'','',0,0),
      (109,'en_PH','English (Philippines)','English (Philippines)',0,0,'','',0,0),
      (110,'en_SG','English (Singapore)','English (Singapore)',0,0,'','',0,0),
      (111,'en_ZA','English (South Africa)','English (South Africa)',0,0,'','',0,0),
      (112,'en_TT','English (Trinidad and Tobago)','English (Trinidad and Tobago)',0,0,'','',0,0),
      (113,'en_UM','English (U.S. Minor Outlying Islands)','English (U.S. Minor Outlying Islands)',0,0,'','',0,0),
      (114,'en_VI','English (U.S. Virgin Islands)','English (U.S. Virgin Islands)',0,0,'','',0,0),
      (115,'en_GB','English (United Kingdom)','English (United Kingdom)',0,0,'','',0,0),
      (116,'en_US','English (United States)','English (United States)',0,0,'','',0,0),
      (117,'en_ZW','English (Zimbabwe)','English (Zimbabwe)',0,0,'','',0,0),
      (118,'en','English','English',1,1,'','',***LANGEN***,0),
      (119,'eo','Esperanto','Esperanto',0,0,'','',0,0),
      (120,'et_EE','Eesti keel (Eesti)','Estonian (Estonia)',0,0,'','',0,0),
      (121,'et','Eesti keel','Estonian',0,0,'','',0,0),
      (122,'ee_GH','','Ewe (Ghana)',0,0,'','',0,0),
      (123,'ee_TG','','Ewe (Togo)',0,0,'','',0,0),
      (124,'ee','','Ewe',0,0,'','',0,0),
      (125,'fo_FO','','Faroese (Faroe Islands)',0,0,'','',0,0),
      (126,'fo','','Faroese',0,0,'','',0,0),
      (127,'fil_PH','Filipino (Pilipinas)','Filipino (Philippines)',0,0,'','',0,0),
      (128,'fil','Filipino','Filipino',0,0,'','',0,0),
      (129,'fi_FI','Suomi (Suomi)','Finnish (Finland)',0,0,'','',0,0),
      (130,'fi','Suomi','Finnish',0,0,'','',0,0),
      (131,'fr_BE','Français (Belgique)','French (Belgium)',0,0,'','',0,0),
      (132,'fr_BJ','Français (Bénin)','French (Benin)',0,0,'','',0,0),
      (133,'fr_BF','Française (Burkina Faso)','French (Burkina Faso)',0,0,'','',0,0),
      (134,'fr_BI','Français (Burundi)','French (Burundi)',0,0,'','',0,0),
      (135,'fr_CM','Français (Cameroun)','French (Cameroon)',0,0,'','',0,0),
      (136,'fr_CA','Français (Canada)','French (Canada)',0,0,'','',0,0),
      (137,'fr_CF','Français (République centrafricaine)','French (Central African Republic)',0,0,'','',0,0),
      (138,'fr_TD','Français (Tchad)','French (Chad)',0,0,'','',0,0),
      (139,'fr_KM','Français (Comores)','French (Comoros)',0,0,'','',0,0),
      (140,'fr_CG','Français (Congo - Brazzaville)','French (Congo - Brazzaville)',0,0,'','',0,0),
      (141,'fr_CD','Français (Congo - Kinshasa)','French (Congo - Kinshasa)',0,0,'','',0,0),
      (142,'fr_CI','Français (Côte d’Ivoire)','French (Côte d’Ivoire)',0,0,'','',0,0),
      (143,'fr_DJ','Français (Djibouti)','French (Djibouti)',0,0,'','',0,0),
      (144,'fr_GQ','Français (Guinée équatoriale)','French (Equatorial Guinea)',0,0,'','',0,0),
      (145,'fr_FR','Français (Francaise)','French (France)',0,0,'','',0,0),
      (146,'fr_GA','Français (Gabon)','French (Gabon)',0,0,'','',0,0),
      (147,'fr_GP','Français (Guadeloupe)','French (Guadeloupe)',0,0,'','',0,0),
      (148,'fr_GN','Français (Guinée)','French (Guinea)',0,0,'','',0,0),
      (149,'fr_LU','Français (Luxembourg)','French (Luxembourg)',0,0,'','',0,0),
      (150,'fr_MG','Français (Madagascar)','French (Madagascar)',0,0,'','',0,0),
      (151,'fr_ML','Française (Mali)','French (Mali)',0,0,'','',0,0),
      (152,'fr_MQ','Français (martinique)','French (Martinique)',0,0,'','',0,0),
      (153,'fr_MC','Français (Monaco)','French (Monaco)',0,0,'','',0,0),
      (154,'fr_NE','Français (Niger)','French (Niger)',0,0,'','',0,0),
      (155,'fr_RW','Français (Rwanda)','French (Rwanda)',0,0,'','',0,0),
      (156,'fr_RE','Français (Réunion)','French (Réunion)',0,0,'','',0,0),
      (157,'fr_BL','Français (Saint Barthélemy)','French (Saint Barthélemy)',0,0,'','',0,0),
      (158,'fr_MF','Français (Saint Martin)','French (Saint Martin)',0,0,'','',0,0),
      (159,'fr_SN','Français (Sénégal)','French (Senegal)',0,0,'','',0,0),
      (160,'fr_CH','Français (Suisse)','French (Switzerland)',0,0,'','',0,0),
      (161,'fr_TG','Français (Togo)','French (Togo)',0,0,'','',0,0),
      (162,'fr','Français','French',1,0,'','',***LANGFR***,0),
      (163,'ff_SN','','Fulah (Senegal)',0,0,'','',0,0),
      (164,'ff','','Fulah',0,0,'','',0,0),
      (165,'gl_ES','Galego (España)','Galician (Spain)',0,0,'','',0,0),
      (166,'gl','Galego','Galician',0,0,'','',0,0),
      (167,'lg_UG','','Ganda (Uganda)',0,0,'','',0,0),
      (168,'lg','','Ganda',0,0,'','',0,0),
      (169,'ka_GE','ქართული (საქართველო)','Georgian (Georgia)',0,0,'','',0,0),
      (170,'ka','ქართული','Georgian',0,0,'','',0,0),
      (171,'de_AT','Deutsch (Österreich)','German (Austria)',0,0,'','',0,0),
      (172,'de_BE','Deutsch (Belgien)','German (Belgium)',0,0,'','',0,0),
      (173,'de_DE','Deutsch (Deutschland)','German (Germany)',0,0,'','',0,0),
      (174,'de_LI','Deutsch (Liechtenstein)','German (Liechtenstein)',0,0,'','',0,0),
      (175,'de_LU','Deutsch (Luxemburg)','German (Luxembourg)',0,0,'','',0,0),
      (176,'de_CH','Deutsch (Schweiz)','German (Switzerland)',0,0,'','',0,0),
      (177,'de','Deutsch','German',1,0,'','',***LANGDE***,0),
      (178,'el_CY','Ελληνικά (Κύπρος)','Greek (Cyprus)',0,0,'','',0,0),
      (179,'el_GR','Ελληνική (Ελλάδα)','Greek (Greece)',0,0,'','',0,0),
      (180,'el','Ελληνική','Greek',0,0,'','',0,0),
      (181,'gu_IN','ગુજરાતી (ભારત)','Gujarati (India)',0,0,'','',0,0),
      (182,'gu','ગુજરાતી','Gujarati',0,0,'','',0,0),
      (183,'guz_KE','','Gusii (Kenya)',0,0,'','',0,0),
      (184,'guz','','Gusii',0,0,'','',0,0),
      (185,'ha_Latn','Hausa (Latin)','Hausa (Latin)',0,0,'','',0,0),
      (186,'ha_Latn_GH','Hausa (Latin, Ghana)','Hausa (Latin, Ghana)',0,0,'','',0,0),
      (187,'ha_Latn_NE','Hausa (Latin, Nijar)','Hausa (Latin, Niger)',0,0,'','',0,0),
      (188,'ha_Latn_NG','Hausa (Latin, Nigeria)','Hausa (Latin, Nigeria)',0,0,'','',0,0),
      (189,'ha','Hausa','Hausa',0,0,'','',0,0),
      (190,'haw_US','Hawaiian (United States)','Hawaiian (United States)',0,0,'','',0,0),
      (191,'haw','Hawaiian','Hawaiian',0,0,'','',0,0),
      (192,'he_IL','עברית (ישראל)','Hebrew (Israel)',0,0,'','',0,0),
      (193,'he','עברית','Hebrew',0,0,'','',0,0),
      (194,'hi_IN','हिंदी (भारत)','Hindi (India)',0,0,'','',0,0),
      (195,'hi','हिंदी','Hindi',0,0,'','',0,0),
      (196,'hu_HU','Magyar (magyar)','Hungarian (Hungary)',0,0,'','',0,0),
      (197,'hu','Magyar','Hungarian',0,0,'','',0,0),
      (198,'is_IS','Íslenska (Ísland)','Icelandic (Iceland)',0,0,'','',0,0),
      (199,'is','Íslenska','Icelandic',0,0,'','',0,0),
      (200,'ig_NG','','Igbo (Nigeria)',0,0,'','',0,0),
      (201,'ig','','Igbo',0,0,'','',0,0),
      (202,'id_ID','Indonesia (Indonesia)','Indonesian (Indonesia)',0,0,'','',0,0),
      (203,'id','Indonesia','Indonesian',0,0,'','',0,0),
      (204,'ga_IE','Gaeilge (Éire)','Irish (Ireland)',0,0,'','',0,0),
      (205,'ga','Gaeilge','Irish',0,0,'','',0,0),
      (206,'it_IT','Italiano (Italia)','Italian (Italy)',0,0,'','',0,0),
      (207,'it_CH','Italiano (Svizzera)','Italian (Switzerland)',0,0,'','',0,0),
      (208,'it','Italiano','Italian',1,0,'','',***LANGIT***,0),
      (209,'ja_JP','日本（日本）','Japanese (Japan)',0,0,'','',0,0),
      (210,'ja','日本','Japanese',0,0,'','',0,0),
      (211,'kea_CV','','Kabuverdianu (Cape Verde)',0,0,'','',0,0),
      (212,'kea','','Kabuverdianu',0,0,'','',0,0),
      (213,'kab_DZ','','Kabyle (Algeria)',0,0,'','',0,0),
      (214,'kab','','Kabyle',0,0,'','',0,0),
      (215,'kl_GL','','Kalaallisut (Greenland)',0,0,'','',0,0),
      (216,'kl','','Kalaallisut',0,0,'','',0,0),
      (217,'kln_KE','','Kalenjin (Kenya)',0,0,'','',0,0),
      (218,'kln','','Kalenjin',0,0,'','',0,0),
      (219,'kam_KE','','Kamba (Kenya)',0,0,'','',0,0),
      (220,'kam','','Kamba',0,0,'','',0,0),
      (221,'kn_IN','ಕನ್ನಡ (ಭಾರತ)','Kannada (India)',0,0,'','',0,0),
      (222,'kn','ಕನ್ನಡ','Kannada',0,0,'','',0,0),
      (223,'kk_Cyrl','Қазақ (кириллица)','Kazakh (Cyrillic)',0,0,'','',0,0),
      (224,'kk_Cyrl_KZ','Қазақ (кириллица, Қазақстан)','Kazakh (Cyrillic, Kazakhstan)',0,0,'','',0,0),
      (225,'kk','Қазақ','Kazakh',0,0,'','',0,0),
      (226,'km_KH','ភាសាខ្មែរ (កម្ពុជា)','Khmer (Cambodia)',0,0,'','',0,0),
      (227,'km','ភាសាខ្មែរ','Khmer',0,0,'','',0,0),
      (228,'ki_KE','','Kikuyu (Kenya)',0,0,'','',0,0),
      (229,'ki','','Kikuyu',0,0,'','',0,0),
      (230,'rw_RW','','Kinyarwanda (Rwanda)',0,0,'','',0,0),
      (231,'rw','','Kinyarwanda',0,0,'','',0,0),
      (232,'kok_IN','','Konkani (India)',0,0,'','',0,0),
      (233,'kok','','Konkani',0,0,'','',0,0),
      (234,'ko_KR','크메르 (캄보디아)','Korean (South Korea)',0,0,'','',0,0),
      (235,'ko','크메르','Korean',0,0,'','',0,0),
      (236,'khq_ML','','Koyra Chiini (Mali)',0,0,'','',0,0),
      (237,'khq','','Koyra Chiini',0,0,'','',0,0),
      (238,'ses_ML','','Koyraboro Senni (Mali)',0,0,'','',0,0),
      (239,'ses','','Koyraboro Senni',0,0,'','',0,0),
      (240,'lag_TZ','','Langi (Tanzania)',0,0,'','',0,0),
      (241,'lag','','Langi',0,0,'','',0,0),
      (242,'lv_LV','Latviešu (Valoda)','Latvian (Latvia)',0,0,'','',0,0),
      (243,'lv','Latviešu','Latvian',0,0,'','',0,0),
      (244,'lt_LT','Lietuvis (Lietuva)','Lithuanian (Lithuania)',0,0,'','',0,0),
      (245,'lt','Lietuvis','Lithuanian',0,0,'','',0,0),
      (246,'luo_KE','','Luo (Kenya)',0,0,'','',0,0),
      (247,'luo','','Luo',0,0,'','',0,0),
      (248,'luy_KE','','Luyia (Kenya)',0,0,'','',0,0),
      (249,'luy','','Luyia',0,0,'','',0,0),
      (250,'mk_MK','Македонски (Македонија)','Macedonian (Macedonia)',0,0,'','',0,0),
      (251,'mk','Македонски','Macedonian',0,0,'','',0,0),
      (252,'jmc_TZ','','Machame (Tanzania)',0,0,'','',0,0),
      (253,'jmc','','Machame',0,0,'','',0,0),
      (254,'kde_TZ','','Makonde (Tanzania)',0,0,'','',0,0),
      (255,'kde','','Makonde',0,0,'','',0,0),
      (256,'mg_MG','Malagasy (Madagascar)','Malagasy (Madagascar)',0,0,'','',0,0),
      (257,'mg','Malagasy','Malagasy',0,0,'','',0,0),
      (258,'ms_BN','Melayu (Brunei)','Malay (Brunei)',0,0,'','',0,0),
      (259,'ms_MY','Melayu (Malaysia)','Malay (Malaysia)',0,0,'','',0,0),
      (260,'ms','Melayu','Malay',0,0,'','',0,0),
      (261,'ml_IN','മലയാളം (ഇന്ത്യ)','Malayalam (India)',0,0,'','',0,0),
      (262,'ml','മലയാളം','Malayalam',0,0,'','',0,0),
      (263,'mt_MT','Malti (Malta)','Maltese (Malta)',0,0,'','',0,0),
      (264,'mt','Malti','Maltese',0,0,'','',0,0),
      (265,'gv_GB','','Manx (United Kingdom)',0,0,'','',0,0),
      (266,'gv','','Manx',0,0,'','',0,0),
      (267,'mr_IN','मराठी (भारत)','Marathi (India)',0,0,'','',0,0),
      (268,'mr','मराठी','Marathi',0,0,'','',0,0),
      (269,'mas_KE','','Masai (Kenya)',0,0,'','',0,0),
      (270,'mas_TZ','','Masai (Tanzania)',0,0,'','',0,0),
      (271,'mas','','Masai',0,0,'','',0,0),
      (272,'mer_KE','','Meru (Kenya)',0,0,'','',0,0),
      (273,'mer','','Meru',0,0,'','',0,0),
      (274,'mfe_MU','','Morisyen (Mauritius)',0,0,'','',0,0),
      (275,'mfe','','Morisyen',0,0,'','',0,0),
      (276,'naq_NA','','Nama (Namibia)',0,0,'','',0,0),
      (277,'naq','','Nama',0,0,'','',0,0),
      (278,'ne_IN','नेपाली (भारत)','Nepali (India)',0,0,'','',0,0),
      (279,'ne_NP','नेपाली (नेपाल)','Nepali (Nepal)',0,0,'','',0,0),
      (280,'ne','नेपाली','Nepali',0,0,'','',0,0),
      (281,'nd_ZW','','North Ndebele (Zimbabwe)',0,0,'','',0,0),
      (282,'nd','','North Ndebele',0,0,'','',0,0),
      (283,'nb_NO','Norsk bokmål (norge)','Norwegian Bokmål (Norway)',0,0,'','',0,0),
      (284,'nb','Norsk bokmål','Norwegian Bokmål',0,0,'','',0,0),
      (285,'nn_NO','Norsknorsk (norge)','Norwegian Nynorsk (Norway)',0,0,'','',0,0),
      (286,'nn','Norsknorsk','Norwegian Nynorsk',0,0,'','',0,0),
      (287,'nyn_UG','','Nyankole (Uganda)',0,0,'','',0,0),
      (288,'nyn','','Nyankole',0,0,'','',0,0),
      (289,'or_IN','','Oriya (India)',0,0,'','',0,0),
      (290,'or','','Oriya',0,0,'','',0,0),
      (291,'om_ET','','Oromo (Ethiopia)',0,0,'','',0,0),
      (292,'om_KE','','Oromo (Kenya)',0,0,'','',0,0),
      (293,'om','','Oromo',0,0,'','',0,0),
      (294,'ps_AF','پښتو (افغانستان)','Pashto (Afghanistan)',0,0,'','',0,0),
      (295,'ps','پښتو','Pashto',0,0,'','',0,0),
      (296,'fa_AF','فارسی (افغانستان)','Persian (Afghanistan)',0,0,'','',0,0),
      (297,'fa_IR','فارسی (ایران)','Persian (Iran)',0,0,'','',0,0),
      (298,'fa','فارسی ','Persian',0,0,'','',0,0),
      (299,'pl_PL','Polski (Polska)','Polish (Poland)',0,0,'','',0,0),
      (300,'pl','Polski','Polish',0,0,'','',0,0),
      (301,'pt_BR','Português (Brasil)','Portuguese (Brazil)',0,0,'','',0,0),
      (302,'pt_GW','Português (Guiné-Bissau)','Portuguese (Guinea-Bissau)',0,0,'','',0,0),
      (303,'pt_MZ','Português (Moçambique)','Portuguese (Mozambique)',0,0,'','',0,0),
      (304,'pt_PT','Português (Portugal)','Portuguese (Portugal)',0,0,'','',0,0),
      (305,'pt','Português','Portuguese',0,0,'','',0,0),
      (306,'pa_Arab','ਪੰਜਾਬੀ (ਅਰਬੀ)','Punjabi (Arabic)',0,0,'','',0,0),
      (307,'pa_Arab_PK','ਪੰਜਾਬੀ (ਅਰਬੀ, ਪਾਕਿਸਤਾਨ)','Punjabi (Arabic, Pakistan)',0,0,'','',0,0),
      (308,'pa_Guru','ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ)','Punjabi (Gurmukhi)',0,0,'','',0,0),
      (309,'pa_Guru_IN','ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ, ਭਾਰਤ)','Punjabi (Gurmukhi, India)',0,0,'','',0,0),
      (310,'pa','ਪੰਜਾਬੀ','Punjabi',0,0,'','',0,0),
      (311,'ro_MD','Română (Moldova)','Romanian (Moldova)',0,0,'','',0,0),
      (312,'ro_RO','Română (România)','Romanian (Romania)',0,0,'','',0,0),
      (313,'ro','Română','Romanian',0,0,'','',0,0),
      (314,'rm_CH','','Romansh (Switzerland)',0,0,'','',0,0),
      (315,'rm','','Romansh',0,0,'','',0,0),
      (316,'rof_TZ','','Rombo (Tanzania)',0,0,'','',0,0),
      (317,'rof','','Rombo',0,0,'','',0,0),
      (318,'ru_MD','Русский (Молдова)','Russian (Moldova)',0,0,'','',0,0),
      (319,'ru_RU','Русский (Россия)','Russian (Russia)',0,0,'','',0,0),
      (320,'ru_UA','Русский (Украина)','Russian (Ukraine)',0,0,'','',0,0),
      (321,'ru','Русский','Russian',1,0,'','',***LANGRU***,0),
      (322,'rwk_TZ','','Rwa (Tanzania)',0,0,'','',0,0),
      (323,'rwk','','Rwa',0,0,'','',0,0),
      (324,'saq_KE','','Samburu (Kenya)',0,0,'','',0,0),
      (325,'saq','','Samburu',0,0,'','',0,0),
      (326,'sg_CF','','Sango (Central African Republic)',0,0,'','',0,0),
      (327,'sg','','Sango',0,0,'','',0,0),
      (328,'seh_MZ','','Sena (Mozambique)',0,0,'','',0,0),
      (329,'seh','','Sena',0,0,'','',0,0),
      (330,'sr_Cyrl','Српски језик (Ћирилица)','Serbian (Cyrillic)',0,0,'','',0,0),
      (331,'sr_Cyrl_BA','Српски (Ћирилица, Босна и Херцеговина)','Serbian (Cyrillic, Bosnia and Herzegovina)',0,0,'','',0,0),
      (332,'sr_Cyrl_ME','Српски (Ћирилица, Црна Гора)','Serbian (Cyrillic, Montenegro)',0,0,'','',0,0),
      (333,'sr_Cyrl_RS','Српски (Ћирилица, Србија)','Serbian (Cyrillic, Serbia)',0,0,'','',0,0),
      (334,'sr_Latn','','Serbian (Latin)',0,0,'','',0,0),
      (335,'sr_Latn_BA','','Serbian (Latin, Bosnia and Herzegovina)',0,0,'','',0,0),
      (336,'sr_Latn_ME','','Serbian (Latin, Montenegro)',0,0,'','',0,0),
      (337,'sr_Latn_RS','','Serbian (Latin, Serbia)',0,0,'','',0,0),
      (338,'sr','','Serbian',0,0,'','',0,0),
      (339,'sn_ZW','Shona (Zimbabwe)','Shona (Zimbabwe)',0,0,'','',0,0),
      (340,'sn','Shona','Shona',0,0,'','',0,0),
      (341,'ii_CN','','Sichuan Yi (China)',0,0,'','',0,0),
      (342,'ii','','Sichuan Yi',0,0,'','',0,0),
      (343,'si_LK','','Sinhala (Sri Lanka)',0,0,'','',0,0),
      (344,'si','','Sinhala',0,0,'','',0,0),
      (345,'sk_SK','Slovenčina (Slovensko)','Slovak (Slovakia)',0,0,'','',0,0),
      (346,'sk','Slovenčina','Slovak',0,0,'','',0,0),
      (347,'sl_SI','Slovenščina (Slovenija)','Slovenian (Slovenia)',0,0,'','',0,0),
      (348,'sl','Slovenščina','Slovenian',0,0,'','',0,0),
      (349,'xog_UG','','Soga (Uganda)',0,0,'','',0,0),
      (350,'xog','','Soga',0,0,'','',0,0),
      (351,'so_DJ','Somali (Jabuuti)','Somali (Djibouti)',0,0,'','',0,0),
      (352,'so_ET','Somali (Itoobiya)','Somali (Ethiopia)',0,0,'','',0,0),
      (353,'so_KE','Somali (Kenya)','Somali (Kenya)',0,0,'','',0,0),
      (354,'so_SO','Somali (Somali)','Somali (Somalia)',0,0,'','',0,0),
      (355,'so','Somali','Somali',0,0,'','',0,0),
      (356,'es_AR','Español (argentina)','Spanish (Argentina)',0,0,'','',0,0),
      (357,'es_BO','Español (bolivia)','Spanish (Bolivia)',0,0,'','',0,0),
      (358,'es_CL','Español (chile)','Spanish (Chile)',0,0,'','',0,0),
      (359,'es_CO','Español (colombia)','Spanish (Colombia)',0,0,'','',0,0),
      (360,'es_CR','Español (costa rica)','Spanish (Costa Rica)',0,0,'','',0,0),
      (361,'es_DO','Español (republica dominicana)','Spanish (Dominican Republic)',0,0,'','',0,0),
      (362,'es_EC','Español (ecuador)','Spanish (Ecuador)',0,0,'','',0,0),
      (363,'es_SV','Español (el salvador)','Spanish (El Salvador)',0,0,'','',0,0),
      (364,'es_GQ','Español (guinea ecuatorial)','Spanish (Equatorial Guinea)',0,0,'','',0,0),
      (365,'es_GT','Español (guatemala)','Spanish (Guatemala)',0,0,'','',0,0),
      (366,'es_HN','Español (honduras)','Spanish (Honduras)',0,0,'','',0,0),
      (367,'es_419','Español (latinoamerica)','Spanish (Latin America)',0,0,'','',0,0),
      (368,'es_MX','Español (mexico)','Spanish (Mexico)',0,0,'','',0,0),
      (369,'es_NI','Español (nicaragua)','Spanish (Nicaragua)',0,0,'','',0,0),
      (370,'es_PA','Español (panama)','Spanish (Panama)',0,0,'','',0,0),
      (371,'es_PY','Español (paraguay)','Spanish (Paraguay)',0,0,'','',0,0),
      (372,'es_PE','Español (peru)','Spanish (Peru)',0,0,'','',0,0),
      (373,'es_PR','Español (puerto rico)','Spanish (Puerto Rico)',0,0,'','',0,0),
      (374,'es_ES','Español (españa)','Spanish (Spain)',0,0,'','',0,0),
      (375,'es_US','Español (Estados Unidos)','Spanish (United States)',0,0,'','',0,0),
      (376,'es_UY','Español (uruguay)','Spanish (Uruguay)',0,0,'','',0,0),
      (377,'es_VE','Español (venezuela)','Spanish (Venezuela)',0,0,'','',0,0),
      (378,'es','Español','Spanish',1,0,'','',***LANGES***,0),
      (379,'sw_KE','','Swahili (Kenya)',0,0,'','',0,0),
      (380,'sw_TZ','','Swahili (Tanzania)',0,0,'','',0,0),
      (381,'sw','','Swahili',0,0,'','',0,0),
      (382,'sv_FI','Svenska (finska)','Swedish (Finland)',0,0,'','',0,0),
      (383,'sv_SE','Svenska (sverige)','Swedish (Sweden)',0,0,'','',0,0),
      (384,'sv','Svenska','Swedish',0,0,'','',0,0),
      (385,'gsw_CH','','Swiss German (Switzerland)',0,0,'','',0,0),
      (386,'gsw','','Swiss German',0,0,'','',0,0),
      (387,'shi_Latn','','Tachelhit (Latin)',0,0,'','',0,0),
      (388,'shi_Latn_MA','','Tachelhit (Latin, Morocco)',0,0,'','',0,0),
      (389,'shi_Tfng','','Tachelhit (Tifinagh)',0,0,'','',0,0),
      (390,'shi_Tfng_MA','','Tachelhit (Tifinagh, Morocco)',0,0,'','',0,0),
      (391,'shi','','Tachelhit',0,0,'','',0,0),
      (392,'dav_KE','','Taita (Kenya)',0,0,'','',0,0),
      (393,'dav','','Taita',0,0,'','',0,0),
      (394,'ta_IN','தமிழ் (இந்தியா)','Tamil (India)',0,0,'','',0,0),
      (395,'ta_LK','தமிழ் (இந்தியா)','Tamil (Sri Lanka)',0,0,'','',0,0),
      (396,'ta','தமிழ்','Tamil',0,0,'','',0,0),
      (397,'te_IN','తెలుగు (భారతదేశం)','Telugu (India)',0,0,'','',0,0),
      (398,'te','తెలుగు','Telugu',0,0,'','',0,0),
      (399,'teo_KE','','Teso (Kenya)',0,0,'','',0,0),
      (400,'teo_UG','','Teso (Uganda)',0,0,'','',0,0),
      (401,'teo','','Teso',0,0,'','',0,0),
      (402,'th_TH','ไทย (ไทยแลนด์)','Thai (Thailand)',0,0,'','',0,0),
      (403,'th','ไทย','Thai',0,0,'','',0,0),
      (404,'bo_CN','','Tibetan (China)',0,0,'','',0,0),
      (405,'bo_IN','','Tibetan (India)',0,0,'','',0,0),
      (406,'bo','','Tibetan',0,0,'','',0,0),
      (407,'ti_ER','','Tigrinya (Eritrea)',0,0,'','',0,0),
      (408,'ti_ET','','Tigrinya (Ethiopia)',0,0,'','',0,0),
      (409,'ti','','Tigrinya',0,0,'','',0,0),
      (410,'to_TO','','Tonga (Tonga)',0,0,'','',0,0),
      (411,'to','','Tonga',0,0,'','',0,0),
      (412,'tr_TR','Türkçe (Türkiye)','Turkish (Turkey)',0,0,'','',0,0),
      (413,'tr','Türkçe','Turkish',0,0,'','',0,0),
      (414,'uk_UA','Українська (українська)','Ukrainian (Ukraine)',0,0,'','',0,0),
      (415,'uk','Українська','Ukrainian',0,0,'','',0,0),
      (416,'ur_IN','اردو (بھارت)','Urdu (India)',0,0,'','',0,0),
      (417,'ur_PK','اردو (پاکستان)','Urdu (Pakistan)',0,0,'','',0,0),
      (418,'ur','اردو','Urdu',0,0,'','',0,0),
      (419,'uz_Arab','','Uzbek (Arabic)',0,0,'','',0,0),
      (420,'uz_Arab_AF','','Uzbek (Arabic, Afghanistan)',0,0,'','',0,0),
      (421,'uz_Cyrl','','Uzbek (Cyrillic)',0,0,'','',0,0),
      (422,'uz_Cyrl_UZ','','Uzbek (Cyrillic, Uzbekistan)',0,0,'','',0,0),
      (423,'uz_Latn','O\'zbek (lotin)','Uzbek (Latin)',0,0,'','',0,0),
      (424,'uz_Latn_UZ','O\'zbek (Lotin, O\'zbekiston)','Uzbek (Latin, Uzbekistan)',0,0,'','',0,0),
      (425,'uz','O\'zbek','Uzbek',0,0,'','',0,0),
      (426,'vi_VN','Tiếng Việt (Việt Nam)','Vietnamese (Vietnam)',0,0,'','',0,0),
      (427,'vi','Tiếng Việt','Vietnamese',0,0,'','',0,0),
      (428,'vun_TZ','','Vunjo (Tanzania)',0,0,'','',0,0),
      (429,'vun','','Vunjo',0,0,'','',0,0),
      (430,'cy_GB','Cymraeg (Y Deyrnas Unedig)','Welsh (United Kingdom)',0,0,'','',0,0),
      (431,'cy','Cymraeg','Welsh',0,0,'','',0,0),
      (432,'yo_NG','Yorùbá (Nigeria)','Yoruba (Nigeria)',0,0,'','',0,0),
      (433,'yo','Yorùbá','Yoruba',0,0,'','',0,0),
      (434,'zu_ZA','IsiZulu (eNingizimu Afrika)','Zulu (South Africa)',0,0,'','',0,0),
      (435,'zu','IsiZulu','Zulu\r\n',0,0,'','',0,0)",

    // Create table "appnetos_header".
    "DROP TABLE IF EXISTS `***PREFIX***_appnetos__header_103`",
    "CREATE TABLE `***PREFIX***_appnetos__header_103` (
      `xt_id` int(10) NOT NULL AUTO_INCREMENT,
      `xt_parent_id` int(10) NOT NULL DEFAULT '0',
      `xt_active` tinyint(4) NOT NULL DEFAULT '1',
      `xt_language_key` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
      `xt_logo` tinyint(4) NOT NULL DEFAULT '0',
      `xt_sort` int(10) NOT NULL DEFAULT '0',
      `xt_img` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
      `xt_link` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
      `xt_width` int(10) NOT NULL DEFAULT '0',
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='APPNET OS Header.'",

    // Insert into table "appnetos_header".
    "INSERT INTO `***PREFIX***_appnetos__header_103` VALUES 
      (1,0,1,'global',1,0,'svg','1',160),
      (2,0,1,'global',0,3,'svg','https://www.youtube.com/channel/UCheq8bwOqtFg-_2qY_9HJgQ',36),
      (3,0,1,'global',0,1,'svg','https://www.facebook.com/appnetos',36),
      (4,0,1,'global',0,2,'svg','https://twitter.com/appnetos',36)",

    // Create table "appnetos_navbar".
    "DROP TABLE IF EXISTS `***PREFIX***_appnetos__navbar_102`",
    "CREATE TABLE `***PREFIX***_appnetos__navbar_102` (
      `xt_id` int(10) NOT NULL AUTO_INCREMENT,
      `xt_parent_id` int(10) NOT NULL DEFAULT '0',
      `xt_language_key` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
      `xt_sort` int(10) NOT NULL DEFAULT '0',
      `xt_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
      `xt_link` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='APPNET OS Navabar.'",

    // Insert into table "appnetos_navbar".
    "INSERT INTO `***PREFIX***_appnetos__navbar_102` VALUES 
      (19,0,'global',1,'Admin Section','/***URI***/admin'),
      (20,19,'de',0,'Admin-Bereich',''),
      (21,19,'es',0,'Sección de administración',''),
      (22,19,'fr',0,'Section Administrateur',''),
      (23,19,'it',0,'Sezione Amministratore',''),
      (24,19,'ru',0,'Секция администратора',''),
      (25,0,'global',2,'Demo',''),
      (26,25,'global',1,'Sign in','2'),
      (27,25,'global',2,'Sign up','8'),
      (28,25,'global',3,'Forgotten password','14'),
      (29,28,'de',0,'Passwort vergessen',''),
      (30,28,'es',0,'Contraseña olvidada',''),
      (31,28,'fr',0,'Mot de passe oublié',''),
      (32,28,'it',0,'Password dimenticata',''),
      (33,28,'ru',0,'Забытый пароль',''),
      (34,27,'de',0,'Registrieren',''),
      (35,27,'es',0,'Registro',''),
      (36,27,'fr',0,'S’inscrire',''),
      (37,27,'it',0,'Registro',''),
      (38,27,'ru',0,'Зарегистрировать',''),
      (39,26,'de',0,'Anmelden',''),
      (40,26,'es',0,'Inicia sesión',''),
      (41,26,'fr',0,'Connexion',''),
      (42,26,'it',0,'Accedi',''),
      (43,26,'ru',0,'Войти',''),
      (44,25,'de',0,'Demo',''),
      (45,25,'en',0,'Demo',''),
      (46,25,'es',0,'Demo',''),
      (47,25,'fr',0,'Démo',''),
      (48,25,'it',0,'Demo',''),
      (49,25,'ru',0,'Демо','')",

    // Create table "appnetos_carousel".
    "DROP TABLE IF EXISTS `***PREFIX***_appnetos__carousel_104`",
    "CREATE TABLE IF NOT EXISTS `***PREFIX***_appnetos__carousel_104` (
    `xt_id` int(10) NOT NULL AUTO_INCREMENT,
      `xt_parent_id` int(10) NOT NULL DEFAULT '0',
      `xt_language_key` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
      `xt_sort` int(10) NOT NULL DEFAULT '0',
      `xt_img` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
      `xt_link` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
      PRIMARY KEY (`xt_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; COMMENT='APPNET OS Carousel.';",
];
